### ISSUE TITLE
关于MAT BBS 接入“酷安黑名单”的说明

### ISSUE THREAD

**Issue by guozixi** [neoFelhz/blacklist_coolapk#2]
**由于此黑名单的诸多争议，本说明作废。**

[MAT BBS](https://mat.letitfly.me/) = [My Android Tools BBS](https://mat.letitfly.me/)
唯一地址：https://mat.letitfly.me/

我会**不定期**将“酷安黑名单”加入
MAT BBS的禁止注册关键字。

如果有人通过申诉被“黑名单”除名，
我也会**抽空**解除对其ID的注册限制。

> 如果有已经在MAT BBS注册的**同名用户**，
> 因为并不能确定就是那个人，
> 所以，在其**没有**违反论坛规定的情况下，
> **不**处理。

这**通常不会**给MAT BBS新用户带来不便，
只是不能以**酷安已知喷子的ID**注册罢了。

~~已部署黑名单，最近一次部署时间：2016.10.15~~
由于已启用崭新的**技术向**注册验证问答，
MAT BBS即日起（2017.1.20）
不再执行对此黑名单的同名ID禁止注册的限制。

**Comment by neoFelhz** [comment]
设置几个label

**Comment by OliverDH** [comment]
66666

**Comment by guozixi** [comment]
@OliverDH 虽然不能完全禁绝喷子，但是总不能什么都不做。

**Comment by yingfeng-studio** [comment]
酷安黑名单这个到底是什么鬼  上次在酷市场谁要转载你艾特我就看到了

**Comment by OliverDH** [comment]
感觉像是节奏狗之流的吧。一天到晚导出恶心人，然后被酷安拉黑？

2016-10-07 23:53 GMT+08:00 demon <notifications@github.com>:
