### ISSUE TITLE
建议增加规则：已知道自己进入黑名单，但就黑名单一事继续对酷友恶语相向的，永不接受申诉

### ISSUE THREAD

**Issue by guozixi** [neoFelhz/blacklist_coolapk#5]
酷友，泛指酷安网 ([coolapk.com](http://www.coolapk.com/)) 的用户，
当然也包括 黑名单发起者 和 联动执行者

**Comment by neoFelhz** [comment]
我觉得这个规则没有必要。
如果那种人，因为黑名单而对我恶语相向，我本人不在乎；
因为黑名单而对其它酷友恶语相向，则是触犯了现有的黑名单规则。
对于永不接受申诉，我已经设立了“三进宫机制”。
而且那种人，是“不屑于”来这里申诉的，没有必要专门为此加条规则。

**Comment by guozixi** [comment]
@neoFelhz 嗯，好的
