### ISSUE TITLE
关于 让技术飞(letitfly.me) 接入本黑名单的说明

### ISSUE THREAD

**Issue by guozixi** [neoFelhz/blacklist_coolapk#6]
由于此黑名单的诸多争议，此说明作废！

[让技术飞](https://letitfly.me) 即我的博客，地址：[https://letitfly.me](https://letitfly.me)
我会**不定期**将“酷安黑名单”加入
博客的评论黑名单，**禁止**同名ID评论我的博客。

如果有人通过申诉被“黑名单”除名，
我也会**抽空**解除对其ID的限制。

这通常**不会**给访客带来不便，
那些人并不会在乎一个小站。你们说呢？

~~已部署黑名单，最近一次部署时间：2016.10.15~~
由于我的小站并没有多少评论，
停止执行此黑名单。
反正，我一直开着评论审核呢o(∩_∩)o

**Comment by neoFelhz** [comment]
你可以fork我的项目然后修改声明，然后在我的项目这边Open pull request，我合并就好。
